### PR TITLE
Add test for Bookmark.all_tags_with_counts

### PR DESCRIPTION
**Pull request by Ian-Foote**

### CODE REVIEW

**Comment by Ian-Foote** [comment]
@incuna/backend Review?

**Comment by KevinEtienne** [comment]
Looks good to me, but maybe #9 should be merged first

**Comment by Ian-Foote** [comment]
Updated.

**Comment by adam-thomas** [comment]
`django.db.utils.ProgrammingError: relation "auth_user" does not exist` hmm.  That sounds vaguely like the `contenttypes` error, maybe it does need to be above `admin` as well?

**Comment by adam-thomas** [comment]
I just noticed that in `incuna-groups` it's

```
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
```

ie. `auth` above `admin`.  Looks like that might fix the issue.

**Comment by adam-thomas** [comment]
https://github.com/incuna/base-library/pull/4 fyi (assuming I'm not missing something)

**Comment by Ian-Foote** [comment]
Fixed.

**Comment by adam-thomas** [comment]
Ace

**Comment by Ian-Foote** [comment]
@incuna/backend Merge?

**Comment by adam-thomas** [comment]
Was just looking sorry, LGTM :)

**Pull request merged**
